### PR TITLE
Ensure that `truncate()` always returns a string as documented.

### LINKED ISSUE #44: Wrong return type for `truncate()`
The `truncate()` function is documented to have the type:

```ts
function truncate(html: string | CheerioAPI, length?: number | IOptions,  truncateOptions?: IOptions): string {
  // ...
}
```

However, the actual compiled type is:

```ts
function truncate(html: string | CheerioAPI, length?: number | IOptions,  truncateOptions?: IOptions): string | CheerioAPI | null {
  // ...
}
```

The return type is `string | CheerioAPI | null`, not `string` as documented. The documentation should reflect the correct type, or the implementation should return the correct value

### PR DESCRIPTION
**Pull request by Goodwine**
Fixes #44

### CODE REVIEW

File: src/truncate.ts [hunk 1]
```diff
@@ -96,20 +96,20 @@ const defaultOptions: IOptions = {
...
     options.length === Infinity) {
-    return html
+    return isCheerioInstance(html) ? html.html() ?? '' : html;
   }
 
   let $: CheerioAPI
 
   if (isCheerioInstance(html)) {
-    $ = html as CheerioAPI
+    $ = html
```
Comment (oe) [inline src/truncate.ts:112]: 👍

File: test/truncate.spec.ts [hunk 2]
```diff
@@ -16,9 +16,10 @@ describe('Truncate html', () => {
     })
 
     it('should NOT truncate a string if NO length provided $', () => {
-      const html = cheerio.load('string')
+      const html = 'string'
+      const $ = cheerio.load(html)
 
-      expect(truncate(html)).toBe(html)
+      expect(truncate($)).toBe('<html><head></head><body>string</body></html>')
```
Comment (oe) [inline test/truncate.spec.ts:22]: should get rid of wrapper of `html`, `head`, `body`

Comment (oe) [reply test/truncate.spec.ts:22]: cheerio instance provided by external, `truncate` should not take care about the wrappers

**Review by oe — COMMENTED** [review]
Please wait till I check on the device tonight (after 8 p.m. UTC+8 😄)

**Comment by oe** [comment]
`v1.2.1` has been released, please have a try
